# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19N3a81rpfdA5sh2wD9deBlVu99sLvjtd
"""

!pip install trimesh open3d gradio plotly

from google.colab import files
uploaded = files.upload()

import trimesh

# Load the STL file
gear = trimesh.load_mesh("Spur Gear.stl")

# Display basic info
print(gear)

# Visualize the mesh
gear.show()

import trimesh

# Load mesh
gear = trimesh.load_mesh("Spur Gear.stl")

# Evaluation metrics
print("Volume:", gear.volume)
print("Surface Area:", gear.area)
print("Bounding Box (extents):", gear.bounding_box.extents)
print("Number of Vertices:", len(gear.vertices))
print("Number of Faces:", len(gear.faces))
print("Is watertight?", gear.is_watertight)

import gradio as gr
import trimesh
import plotly.graph_objs as go

def analyze_stl(file):
    # Load mesh
    mesh = trimesh.load(file.name)

    # Metrics
    volume = mesh.volume
    area = mesh.area
    bounds = mesh.bounding_box.extents
    num_faces = len(mesh.faces)
    num_vertices = len(mesh.vertices)
    watertight = mesh.is_watertight

    # Plotly 3D preview
    mesh_fig = go.Figure(data=[
        go.Mesh3d(
            x=mesh.vertices[:, 0],
            y=mesh.vertices[:, 1],
            z=mesh.vertices[:, 2],
            i=mesh.faces[:, 0],
            j=mesh.faces[:, 1],
            k=mesh.faces[:, 2],
            color='lightblue',
            opacity=0.5
        )
    ])
    mesh_fig.update_layout(scene=dict(aspectmode='data'))

    # Metrics summary
    summary = (
        f"Volume: {volume:.4f} units³\n"
        f"Surface Area: {area:.4f} units²\n"
        f"Bounding Box: {bounds}\n"
        f"Vertices: {num_vertices}\n"
        f"Faces: {num_faces}\n"
        f"Watertight: {watertight}"
    )

    return summary, mesh_fig

# UI layout
demo = gr.Interface(
    fn=analyze_stl,
    inputs=gr.File(label="Upload STL File"),
    outputs=[
        gr.Textbox(label="Mesh Info"),
        gr.Plot(label="3D Preview")
    ],
    title="STL Mesh Analyzer",
    description="Upload a .stl file to see mesh metrics and a 3D preview"
)

demo.launch()